from functools import partial

from src.modelling.models.modules import efficientnet_b0, efficientnet_b1, efficientnet_b2, efficientnet_b3, \
    efficientnet_b4, efficientnet_b5, efficientnet_b6, efficientnet_b7, efficientnet_v2_s, efficientnet_v2_m, \
    efficientnet_v2_l
from src.modelling.models.modules import mnasnet1_0, mnasnet1_3, mnasnet0_75, mnasnet0_5
from src.modelling.models.modules import resnet152, resnet101, resnet50, resnet34, resnet18
from src.modelling.models.modules import standard
from src.modelling.models.modules import swin_b, swin_s
from src.modelling.models.modules.convnext import convnext_tiny, convnext_small, convnext_base, convnext_large
from src.modelling.models.modules.nopad_efficientnet import nopad_efficientnet_b0, nopad_efficientnet_b1, \
    nopad_efficientnet_b2, nopad_efficientnet_b3, nopad_efficientnet_b4, nopad_efficientnet_b5, nopad_efficientnet_b6, \
    nopad_efficientnet_b7, nopad_efficientnet_v2_s, nopad_efficientnet_v2_m, nopad_efficientnet_v2_l
from src.modelling.models.modules.twoconv_net import twoconvnet
from src.modelling.models.modules.standard import DoubleConvSkip, DoubleConv

backbones = {
    "mnasnet0_5": {
        "model": mnasnet0_5,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "bn_mnasnet",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "mnasnet0_75": {
        "model": mnasnet0_75,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "bn_mnasnet",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "mnasnet": {
        "model": mnasnet1_0,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "bn_mnasnet",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "mnasnet1_0": {
        "model": mnasnet1_0,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "bn_mnasnet",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "mnasnet1_3": {
        "model": mnasnet1_3,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "bn_mnasnet",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "resnet18": {
        "model": resnet18,
        "initial_stride": 2,
        "final_factor": None,
        "final_dropout": None,
        "norm_type": "batchnorm",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "resnet34": {
        "model": resnet34,
        "initial_stride": 2,
        "final_factor": None,
        "final_dropout": None,
        "norm_type": "batchnorm",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "resnet50": {
        "model": resnet50,
        "initial_stride": 2,
        "final_factor": None,
        "final_dropout": None,
        "norm_type": "batchnorm",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "resnet101": {
        "model": resnet101,
        "initial_stride": 2,
        "final_factor": None,
        "final_dropout": None,
        "norm_type": "batchnorm",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "resnet152": {
        "model": resnet152,
        "initial_stride": 2,
        "final_factor": None,
        "final_dropout": None,
        "norm_type": "batchnorm",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },

    "swin_b": {
        "model": swin_b,
        "initial_stride": 4,
        "final_factor": None,
        "final_dropout": None,
        "norm_type": "ln",
        "activation": "gelu",
        "up_block": DoubleConvSkip,
    },
    "swin_s": {
        "model": swin_s,
        "initial_stride": 4,
        "final_factor": None,
        "final_dropout": None,
        "norm_type": "ln",
        "activation": "gelu",
        "up_block": DoubleConvSkip,
    },
    "standard": {
        "model": standard,
        "initial_stride": 1,
        "final_factor": None,
        "final_dropout": 0.2,
        "norm_type": "batchnorm",
        "activation": "relu",
        "up_block": DoubleConvSkip,
    },
    "standard_no_skip": {
        "model": partial(standard, skip_connection=False),
        "initial_stride": 1,
        "final_factor": None,
        "final_dropout": 0.2,
        "norm_type": "batchnorm",
        "activation": "relu",
        "up_block": DoubleConv,
    },
    "efficientnet_b0": {
        "model": efficientnet_b0,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "batchnorm",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_b1": {
        "model": efficientnet_b1,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "batchnorm",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_b2": {
        "model": efficientnet_b2,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.3,
        "norm_type": "batchnorm",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_b3": {
        "model": efficientnet_b3,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.3,
        "norm_type": "batchnorm",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_b4": {
        "model": efficientnet_b4,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.4,
        "norm_type": "batchnorm",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_b5": {
        "model": efficientnet_b5,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.4,
        "norm_type": "bn_efficientnet",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_b6": {
        "model": efficientnet_b6,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.5,
        "norm_type": "bn_efficientnet",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_b7": {
        "model": efficientnet_b7,
        "initial_stride": 2,
        "final_factor": 4,
        "final_dropout": 0.5,
        "norm_type": "bn_efficientnet",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_v2_s": {
        "model": efficientnet_v2_s,
        "initial_stride": 2,
        "final_size": 1280,
        "final_dropout": 0.2,
        "norm_type": "bn_efficientnetv2",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_v2_m": {
        "model": efficientnet_v2_m,
        "initial_stride": 2,
        "final_size": 1280,
        "final_dropout": 0.3,
        "norm_type": "bn_efficientnetv2",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "efficientnet_v2_l": {
        "model": efficientnet_v2_l,
        "initial_stride": 2,
        "final_size": 1280,
        "final_dropout": 0.4,
        "norm_type": "bn_efficientnetv2",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },

    "nopad_efficientnet_b0": {
        "model": nopad_efficientnet_b0,
        "initial_stride": 1,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "batchnorm",
        "activation": "silu",
    },
    "nopad_efficientnet_b1": {
        "model": nopad_efficientnet_b1,
        "initial_stride": 1,
        "final_factor": 4,
        "final_dropout": 0.2,
        "norm_type": "batchnorm",
        "activation": "silu",
    },
    "nopad_efficientnet_b2": {
        "model": nopad_efficientnet_b2,
        "initial_stride": 1,
        "final_factor": 4,
        "final_dropout": 0.3,
        "norm_type": "batchnorm",
        "activation": "silu",
    },
    "nopad_efficientnet_b3": {
        "model": nopad_efficientnet_b3,
        "initial_stride": 1,
        "final_factor": 4,
        "final_dropout": 0.3,
        "norm_type": "batchnorm",
        "activation": "silu",
    },
    "nopad_efficientnet_b4": {
        "model": nopad_efficientnet_b4,
        "initial_stride": 1,
        "final_factor": 4,
        "final_dropout": 0.4,
        "norm_type": "batchnorm",
        "activation": "silu",
    },
    "nopad_efficientnet_b5": {
        "model": nopad_efficientnet_b5,
        "initial_stride": 1,
        "final_factor": 4,
        "final_dropout": 0.4,
        "norm_type": "bn_efficientnet",
        "activation": "silu",
    },
    "nopad_efficientnet_b6": {
        "model": nopad_efficientnet_b6,
        "initial_stride": 1,
        "final_factor": 4,
        "final_dropout": 0.5,
        "norm_type": "bn_efficientnet",
        "activation": "silu",
    },
    "nopad_efficientnet_b7": {
        "model": nopad_efficientnet_b7,
        "initial_stride": 1,
        "final_factor": 4,
        "final_dropout": 0.5,
        "norm_type": "bn_efficientnet",
        "activation": "silu",
    },

    "nopad_efficientnet_v2_s": {
        "model": nopad_efficientnet_v2_s,
        "initial_stride": 2,
        "final_size": 1280,
        "final_dropout": 0.2,
        "norm_type": "bn_efficientnetv2",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "nopad_efficientnet_v2_m": {
        "model": nopad_efficientnet_v2_m,
        "initial_stride": 2,
        "final_size": 1280,
        "final_dropout": 0.3,
        "norm_type": "bn_efficientnetv2",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "nopad_efficientnet_v2_l": {
        "model": nopad_efficientnet_v2_l,
        "initial_stride": 2,
        "final_size": 1280,
        "final_dropout": 0.4,
        "norm_type": "bn_efficientnetv2",
        "activation": "silu",
        "up_block": DoubleConvSkip,
    },
    "convnext_tiny": {
        "model": convnext_tiny,
        "initial_stride": 4,
        "final_factor": 1,
        "norm_type": "layernorm",
        "activation": "gelu",
        "up_block": DoubleConvSkip,
    },
    "convnext_small": {
        "model": convnext_small,
        "initial_stride": 4,
        "final_factor": 1,
        "norm_type": "layernorm",
        "activation": "gelu",
        "up_block": DoubleConvSkip,
    },
    "convnext_base": {
        "model": convnext_base,
        "initial_stride": 4,
        "final_factor": 1,
        "norm_type": "layernorm",
        "activation": "gelu",
        "up_block": DoubleConvSkip,
    },
    "convnext_large": {
        "model": convnext_large,
        "initial_stride": 4,
        "final_factor": 1,
        "norm_type": "layernorm",
        "activation": "gelu",
        "up_block": DoubleConvSkip,
    },
    "twoconv": {
        "model": twoconvnet,
        "initial_stride": 1,
        "final_factor": 1,
        "final_dropout": 0,
        "norm_type": None,
        "activation": None,
        "up_block": DoubleConvSkip,
    },
}
